version: '3'

services:
  web:
    build: .
    command: bash -c 'python3 manage.py runserver 0.0.0.0:8000'
    ports: 
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3307
      - DB_USER=andrewdocker
      - DB_USER_PASSWORD=password
      - DB_NAME=my_database
  mysql:
    image: mysql:8
    environment:
      MYSQL_USER: "andrewdocker"
      MYSQL_DB: "my_database"
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
 
volumes:
  db_data:
