version: '3'

services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - DJANGO_SECRET_KEY:${SECRET_KEY}
      - MYSQL_USER:${DB_USER}
      - NAME:${DB_NAME}
      - PASSWORD:${DB_USER_PASSWORD}
      - HOST:${DB_HOST}
      - PORT:${DB_PORT}
    volumes:
      - db_data:/var/lib/mysql
    depends_on:
      - db
  web:
    build: ./app
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8000:8000"
