version: '3'

services:
  web:
    build: .
    command: bash -c 'python3 manage.py runserver 0.0.0.0:8000'
    ports: 
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - .env
  mysql:
    image: mysql:8
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
 
volumes:
  db_data:
