# Generated by Django 4.2.5 on 2023-10-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IPAddress',
            new_name='Address',
        ),
    ]
